### PR TITLE
Add systemctl daemon-reload

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Comment by alexellis** [comment]
This doesn't seem necessary. It's always worked. Can you show otherwise?

**Comment by frezbo** [comment]
I saw the `daemon-reload` was missing and added it. It might work in user-data, but I had seen `systemctl`  complain to reload when doing it manually.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
What could possibly go wrong? 🙈

**Pull request merged**
